all: main poorwc printit arrays histogram

main: main.c
	gcc -o main main.c

poorwc: poorwc.c
	gcc -o poorwc poorwc.c

printit: printit.c
	gcc -o printit printit.c

arrays: arrays.c
	gcc -o arrays arrays.c

histogram: histogram.c
	gcc -o histogram histogram.c
