all: main lecture exercise1 longest

main: main.c
	gcc main.c -lSDL2 -lSDL2main -o main

lecture: lecture.c
	gcc lecture.c -o lecture

exercise1: exercise1.c
	gcc exercise1.c -o exercise1

longest: longest.c
	gcc longest.c -o longest
