all: histogram histogram-chars char-arrays

histogram:
	gcc -g -Wall -o histogram histogram.c

histogram-chars: histogram-chars.c
	gcc -g -Wall -o histogram-chars histogram-chars.c

char-arrays: char-arrays.c
	gcc -g -o char-arrays char-arrays.c
